version: '3.8'
services:
  jellyfin:
    image: jellyfin/jellyfin:10.8.10
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - "${JELLYFIN_PATH}/config:/config"
      - "${JELLYFIN_PATH}/cache:/cache"
      - "${CONTENT_PATH}:/media"
    ports:
      - 8096:8096
    restart: 'unless-stopped'
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: 'host'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - "${TORRENT_CLIENT_PATH}:/config"
      - "${CONTENT_PATH}:/downloads"
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: 'host'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - "${SONARR_PATH}:/config"
    ports:
      - 8989:8989
    restart: unless-stopped