version: "3.8"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
    volumes:
      - "${JELLYFIN_PATH}:/config"
      - "${CONTENT_PATH}/Series:/data/tvshows"
      - "${CONTENT_PATH}/Movies:/data/movies"
    ports:
      - 8096:8096
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
      - WEBUI_PORT=8080
    volumes:
      - "${TORRENT_CLIENT_PATH}:/config"
      - "${DOWNLOAD_PATH}:/downloads"
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
    volumes:
      - "${PROWLARR_PATH}:/config"
    ports:
      - 9696:9696
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
    volumes:
      - "${SONARR_PATH}:/config"
      - "${CONTENT_PATH}/Series:/tv"
      - "${DOWNLOAD_PATH}:/downloads"
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
    volumes:
      - "${RADARR_PATH}:/config"
      - "${CONTENT_PATH}/Movies:/movies"
      - "${DOWNLOAD_PATH}:/downloads"
    ports:
      - 7878:7878
    restart: unless-stopped