version: '3.8'
services:
  jellyfin:
    image: jellyfin/jellyfin:10.8.10
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - /home/jellyfin/config:/config
      - /home/jellyfin/cache:/cache
      - /home/media:/media
    ports:
      - 8096:8096
    restart: 'unless-stopped'